"""init_db

Revision ID: 92326d6fac6b
Revises: 4def1fe81d81
Create Date: 2024-06-30 17:47:38.589156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92326d6fac6b'
down_revision: Union[str, None] = '4def1fe81d81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('atletas', sa.Column('centro_treinamento_id', sa.Integer(), nullable=False))
    op.drop_constraint('atletas_categoria_id_fkey', 'atletas', type_='foreignkey')
    op.create_foreign_key(None, 'atletas', 'centros_treinamento', ['centro_treinamento_id'], ['pk_id'])
    op.create_foreign_key(None, 'atletas', 'categorias', ['categoria_id'], ['pk_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.drop_constraint(None, 'atletas', type_='foreignkey')
    op.create_foreign_key('atletas_categoria_id_fkey', 'atletas', 'centros_treinamento', ['categoria_id'], ['pk_id'])
    op.drop_column('atletas', 'centro_treinamento_id')
    # ### end Alembic commands ###
